# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3de8126b0b4d219c0140a0eb044ba0693ead58db820cce21048e28ab7088dc33b4565f73eced8f082cd90ef3427bccef85cea03e8427460b51f7b3abeedc9028

test:
  secret_key_base: 2571db6d0aba5426127740443388f959ebaa94477fd80568bac8d6d2a72c68834f58a3ca4d94f422d193c646ed448bd49ec56c937e8b4a304d894a1ddd6583d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
